name: cicd

on:
  push: {}

env:
  MAJOR_MINOR_PATCH: 0.0.1

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure scripts are executable
        run: |
          chmod +x ./bin/compute-semver.sh
          chmod +x ./tests/assert.sh
          chmod +x ./tests/run_tests.sh

      - name: Run tests
        run: bash tests/run_tests.sh

      - name: Compute semantic version
        id: semantic_version
        uses: ./
        with:
          major_minor_patch: ${{ env.MAJOR_MINOR_PATCH }}

      - name: Create semantic versioning git tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ steps.semantic_version.outputs.semantic_version }}",
              sha: context.sha
            })

      - name: Delete outdated git tags
        uses: KinNeko-De/cleanup-outdated-tag-action@v0.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}